// src/views/HomeView.vue
<script setup>
import { onMounted, ref } from "vue";
import { animate, stagger } from "animejs";
import Nav from "../components/Nav.vue";
import { home } from "../../data/site.js";

const data = ref(home);
const grid = ref(null);
const apiBase = import.meta.env.VITE_API_BASE_URL || "";

onMounted(async () => {
  animate(grid.value.querySelectorAll(".card"), {
    opacity: [0, 1],
    translateY: [24, 0],
    delay: stagger(120),
    duration: 700,
    ease: "outBack",
  });

  try {
    const response = await fetch(`${apiBase}/api/profile`);
    if (!response.ok) {
      throw new Error(`主页数据加载失败：${response.status}`);
    }
    data.value = await response.json();
  } catch (error) {
    console.error(error);
  }
});
</script>

<template>
  <section ref="grid" class="dashboard-grid">
    <article class="hero-stage panel-full">
      <Nav />
      <div class="hero-copy">
        <h1 class="hero-display">{{ data.heroTitle }}</h1>
        <p class="hero-subtitle">{{ data.heroSubtitle }}</p>
      </div>
    </article>

    <article class="panel panel-full featured-work-panel card">
      <p class="section-kicker">{{ data.featuredWork.kicker }}</p>
      <p class="featured-title">{{ data.featuredWork.title }}</p>
      <p class="featured-copy">{{ data.featuredWork.copy }}</p>
      <RouterLink class="featured-link" to="/text-lab">
        <span class="featured-link-label">
          {{ data.featuredWork.linkLabel }}
        </span>
        <span class="arrow">›</span>
      </RouterLink>
    </article>

    <article class="panel panel-full identity-panel card">
      <div class="identity-item">
        <p class="section-kicker">座右铭</p>
        <p class="identity-value identity-quote">{{ data.identity.motto }}</p>
      </div>
      <div class="identity-item">
        <p class="section-kicker">正在学习</p>
        <p class="identity-value">{{ data.identity.learning }}</p>
      </div>
    </article>
  </section>
</template>

// components/HomeView.jsx
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import Nav from "./Nav.jsx";
import PageHeading from "./PageHeading.jsx";
import AnimatedCardGrid from "./AnimatedCardGrid.jsx";
import { home } from "../data/site.js";
const API = process.env.NEXT_PUBLIC_API_BASE_URL;

export default function HomeView() {
  const [data, setData] = useState(home);

  useEffect(() => {
    async function loadProfile() {
      try {
        const res = await fetch(`${API}/api/profile`);
        if (!res.ok) {
          throw new Error(`主页数据加载失败：${res.status}`);
        }
        setData(await res.json());
      } catch (error) {
        console.error(error);
      }
    }

    loadProfile();
  }, []);

  return (
    <AnimatedCardGrid className="dashboard-grid">
      <article className="hero-stage panel-full">
        <Nav />
        <PageHeading title={data.heroTitle} subtitle={data.heroSubtitle} />
      </article>

      <article className="panel panel-full featured-work-panel card">
        <p className="section-kicker">{data.featuredWork.kicker}</p>
        <p className="featured-title">{data.featuredWork.title}</p>
        <p className="featured-copy">{data.featuredWork.copy}</p>
        <Link className="featured-link" href="/text-lab">
          <span className="featured-link-label">{data.featuredWork.linkLabel}</span>
          <span className="arrow">›</span>
        </Link>
      </article>

      <article className="panel panel-full identity-panel card">
        <div className="identity-item">
          <p className="section-kicker">座右铭</p>
          <p className="identity-value identity-quote">{data.identity.motto}</p>
        </div>
        <div className="identity-item">
          <p className="section-kicker">正在学习</p>
          <p className="identity-value">{data.identity.learning}</p>
        </div>
      </article>
    </AnimatedCardGrid>
  );
}
